### ISSUE TITLE
selectedLine and selectedTitle don't have the same behavior

### ISSUE THREAD

**Issue by Mycose** [Skyscanner/SkyFloatingLabelTextField#163] opened 2017-08-23 13:26 UTC
# Report

## What did you do?
```
        self.textField.placeholder = "placeholder"
        self.textField.selectedTitle = "selected title"
        self.textField.title = "title"
        self.textField.lineColor = UIColor.red
        self.textField.titleColor = UIColor.red
        self.textField.selectedLineColor = UIColor.blue
        self.textField.selectedTitleColor = UIColor.blue
        self.textField.textAlignment = .right
```

## What did you expect to happen?

I expected that when the textField has focus the title and the line are blue and when the textfield hasn't the focus they are red

## What happened instead?

The title stay blue even after the textfield lost focus but the line goes back to red 

## Environment

Xcode Version: 8.3
SkyFloatingLabelTextField Version: 3.2.0
Deployment Target: 9.0
Base SDK: 10.3
Method of Integration: CocoaPods

## Project that demonstrates the issue

[TestSkyFloatingText.zip](https://github.com/Skyscanner/SkyFloatingLabelTextField/files/1245530/TestSkyFloatingText.zip)

EDIT: Well it's the same bug as #161

**Comment by k0nserv** [comment] 2017-08-31 08:56
Right closing as a dupe of #161 then

**Closed by k0nserv** 2017-08-31 08:56 UTC
